### ISSUE TITLE
Postpositions in Czech UD1.2

### ISSUE THREAD

**Issue by martinpopel** [UniversalDependencies/UD_Czech#1]
http://hdl.handle.net/11346/PMLTQ-Q321

```
a-node $A:= [
  conll/cpos != 'ADP',
  conll/cpos != 'PROPN',
  child a-node [ 
    conll/cpos = 'ADP',
    ord > $A.ord,
    deprel != 'mwe',
  ]
]
```

Most of the instances found by the query above are errors in the conversion of PDT into UD. 

E.g. in "_rozhodnu se tak, jak se rozhodnu, na základě vlastní úvahy_",
_na_ depends on _rozhodnu_ with a non-projective comma (the comma before _jak_) as a child.

**Comment by dan-zeman** [comment]
I went through the first 20 hits and it seems that the real errors are fixed in UD 1.3. The examples I've seen mostly involve the words _pro_ and _proti_, whose usage in these sentences is not prepositional, although they are correctly tagged as prepositions.

There are also instances of foreign phrases. Their annotation is not entirely in accord with the guidelines but that is a different issue and we will hopefully fix it in the future, too.
